import { c } from 'ttag';

export default function getLocalizedTraits(): { [trait: string]: string | undefined } {
  return {
    '???': c('trait').t`???`,
    'AI': c('trait').t`AI`,
    'Abomination': c('trait').t`Abomination`,
    'Abyss': c('trait').t`Abyss`,
    'Act 1': c('trait').t`Act 1`,
    'Act 2': c('trait').t`Act 2`,
    'Agency': c('trait').t`Agency`,
    'Ally': c('trait').t`Ally`,
    'Altered': c('trait').t`Altered`,
    'Ancient': c('trait').t`Ancient`,
    'Ancient One': c('trait').t`Ancient One`,
    'Arkham': c('trait').t`Arkham`,
    'Arkham Asylum': c('trait').t`Arkham Asylum`,
    'Armor': c('trait').t`Armor`,
    'Artist': c('trait').t`Artist`,
    'Assistant': c('trait').t`Assistant`,
    'Attack': c('trait').t`Attack`,
    'Augury': c('trait').t`Augury`,
    'Avatar': c('trait').t`Avatar`,
    'Basement': c('trait').t`Basement`,
    'Bayou': c('trait').t`Bayou`,
    'Believer': c('trait').t`Believer`,
    'Blessed': c('trait').t`Blessed`,
    'Blessed?': c('trait').t`Blessed?`,
    'Blunder': c('trait').t`Blunder`,
    'Boat': c('trait').t`Boat`,
    'Bold': c('trait').t`Bold`,
    'Boon': c('trait').t`Boon`,
    'Bridge': c('trait').t`Bridge`,
    'Broken': c('trait').t`Broken`,
    'Brotherhood': c('trait').t`Brotherhood`,
    'Byakhee': c('trait').t`Byakhee`,
    'Bystander': c('trait').t`Bystander`,
    'Cairo': c('trait').t`Cairo`,
    'Campsite': c('trait').t`Campsite`,
    'Card': c('trait').t`Card`,
    'Carnevale': c('trait').t`Carnevale`,
    'Cave': c('trait').t`Cave`,
    'Central': c('trait').t`Central`,
    'Charm': c('trait').t`Charm`,
    'Chosen': c('trait').t`Chosen`,
    'Circle': c('trait').t`Circle`,
    'City': c('trait').t`City`,
    'Civic': c('trait').t`Civic`,
    'Clairvoyant': c('trait').t`Clairvoyant`,
    'Clothing': c('trait').t`Clothing`,
    'Clover Club': c('trait').t`Clover Club`,
    'Coastal': c('trait').t`Coastal`,
    'Composure': c('trait').t`Composure`,
    'Condition': c('trait').t`Condition`,
    'Connection': c('trait').t`Connection`,
    'Conspirator': c('trait').t`Conspirator`,
    'Construct': c('trait').t`Construct`,
    'Covenant': c('trait').t`Covenant`,
    'Creature': c('trait').t`Creature`,
    'Crime Scene': c('trait').t`Crime Scene`,
    'Criminal': c('trait').t`Criminal`,
    'Cultist': c('trait').t`Cultist`,
    'Curse': c('trait').t`Curse`,
    'Cursed': c('trait').t`Cursed`,
    'Dark Young': c('trait').t`Dark Young`,
    'Deep One': c('trait').t`Deep One`,
    'Depths': c('trait').t`Depths`,
    'Desert': c('trait').t`Desert`,
    'Desperate': c('trait').t`Desperate`,
    'Detective': c('trait').t`Detective`,
    'Developed': c('trait').t`Developed`,
    'Dhole': c('trait').t`Dhole`,
    'Distortion': c('trait').t`Distortion`,
    'Dreamer': c('trait').t`Dreamer`,
    'Dreamlands': c('trait').t`Dreamlands`,
    'Drifter': c('trait').t`Drifter`,
    'Dunwich': c('trait').t`Dunwich`,
    'Eldritch': c('trait').t`Eldritch`,
    'Elite': c('trait').t`Elite`,
    'Endtimes': c('trait').t`Endtimes`,
    'Entrepreneur': c('trait').t`Entrepreneur`,
    'Evidence': c('trait').t`Evidence`,
    'Exhibit': c('trait').t`Exhibit`,
    'Expedition': c('trait').t`Expedition`,
    'Expert': c('trait').t`Expert`,
    'Extradimensional': c('trait').t`Extradimensional`,
    'Extraterrestrial': c('trait').t`Extraterrestrial`,
    'Eztli': c('trait').t`Eztli`,
    'Falcon Point': c('trait').t`Falcon Point`,
    'Familiar': c('trait').t`Familiar`,
    'Fated': c('trait').t`Fated`,
    'Favor': c('trait').t`Favor`,
    'Firearm': c('trait').t`Firearm`,
    'Flaw': c('trait').t`Flaw`,
    'Flora': c('trait').t`Flora`,
    'Footwear': c('trait').t`Footwear`,
    'Forbidden': c('trait').t`Forbidden`,
    'Forgotten': c('trait').t`Forgotten`,
    'Fortune': c('trait').t`Fortune`,
    'Future': c('trait').t`Future`,
    'Gambit': c('trait').t`Gambit`,
    'Geist': c('trait').t`Geist`,
    'Ghast': c('trait').t`Ghast`,
    'Ghoul': c('trait').t`Ghoul`,
    'Government': c('trait').t`Government`,
    'Grant': c('trait').t`Grant`,
    'Graveyard': c('trait').t`Graveyard`,
    'Ground Floor': c('trait').t`Ground Floor`,
    'Guest': c('trait').t`Guest`,
    'Gug': c('trait').t`Gug`,
    'Hall': c('trait').t`Hall`,
    'Hazard': c('trait').t`Hazard`,
    'Hex': c('trait').t`Hex`,
    'Hideout': c('trait').t`Hideout`,
    'Historical Society': c('trait').t`Historical Society`,
    'Human': c('trait').t`Human`,
    'Humanoid': c('trait').t`Humanoid`,
    'Hunter': c('trait').t`Hunter`,
    'Hybrid': c('trait').t`Hybrid`,
    'Illicit': c('trait').t`Illicit`,
    'Improvised': c('trait').t`Improvised`,
    'Injury': c('trait').t`Injury`,
    'Innate': c('trait').t`Innate`,
    'Innocent': c('trait').t`Innocent`,
    'Innsmouth': c('trait').t`Innsmouth`,
    'Insect': c('trait').t`Insect`,
    'Insight': c('trait').t`Insight`,
    'Instrument': c('trait').t`Instrument`,
    'Island': c('trait').t`Island`,
    'Item': c('trait').t`Item`,
    'Job': c('trait').t`Job`,
    'Jungle': c('trait').t`Jungle`,
    'Kadath': c('trait').t`Kadath`,
    'Key': c('trait').t`Key`,
    'Lair': c('trait').t`Lair`,
    'Lead': c('trait').t`Lead`,
    'Leng': c('trait').t`Leng`,
    'Lodge': c('trait').t`Lodge`,
    'Lunatic': c('trait').t`Lunatic`,
    'Madness': c('trait').t`Madness`,
    'Manifold': c('trait').t`Manifold`,
    'Mask': c('trait').t`Mask`,
    'Medic': c('trait').t`Medic`,
    'Melee': c('trait').t`Melee`,
    'Mexico City': c('trait').t`Mexico City`,
    'Mi-Go': c('trait').t`Mi-Go`,
    'Midtown': c('trait').t`Midtown`,
    'Miskatonic': c('trait').t`Miskatonic`,
    'Mnar': c('trait').t`Mnar`,
    'Monster': c('trait').t`Monster`,
    'Montréal': c('trait').t`Montréal`,
    'Mountain': c('trait').t`Mountain`,
    'Mutated': c('trait').t`Mutated`,
    'Mystery': c('trait').t`Mystery`,
    'New Orleans': c('trait').t`New Orleans`,
    'New York City': c('trait').t`New York City`,
    'Nightgaunt': c('trait').t`Nightgaunt`,
    'Nostalgia II': c('trait').t`Nostalgia II`,
    'Obstacle': c('trait').t`Obstacle`,
    'Occult': c('trait').t`Occult`,
    'Ocean': c('trait').t`Ocean`,
    'Omen': c('trait').t`Omen`,
    'Ooth-Nargai': c('trait').t`Ooth-Nargai`,
    'Ooze': c('trait').t`Ooze`,
    'Oozified': c('trait').t`Oozified`,
    'Oriab': c('trait').t`Oriab`,
    'Otherworld': c('trait').t`Otherworld`,
    'Pact': c('trait').t`Pact`,
    'Paradox': c('trait').t`Paradox`,
    'Paris': c('trait').t`Paris`,
    'Part 1': c('trait').t`Part 1`,
    'Passageway': c('trait').t`Passageway`,
    'Patron': c('trait').t`Patron`,
    'Performer': c('trait').t`Performer`,
    'Pnakotus': c('trait').t`Pnakotus`,
    'Poison': c('trait').t`Poison`,
    'Police': c('trait').t`Police`,
    'Port': c('trait').t`Port`,
    'Portal': c('trait').t`Portal`,
    'Power': c('trait').t`Power`,
    'Practiced': c('trait').t`Practiced`,
    'Present-Day': c('trait').t`Present-Day`,
    'Prison': c('trait').t`Prison`,
    'Private': c('trait').t`Private`,
    'Providence': c('trait').t`Providence`,
    'Rail': c('trait').t`Rail`,
    'Ranged': c('trait').t`Ranged`,
    'Relic': c('trait').t`Relic`,
    'Reporter': c('trait').t`Reporter`,
    'Research': c('trait').t`Research`,
    'Resolute': c('trait').t`Resolute`,
    'Retired': c('trait').t`Retired`,
    'Return': c('trait').t`Return`,
    'Ritual': c('trait').t`Ritual`,
    'Ritual Site': c('trait').t`Ritual Site`,
    'River': c('trait').t`River`,
    'Riverside': c('trait').t`Riverside`,
    'Road': c('trait').t`Road`,
    'Royalty': c('trait').t`Royalty`,
    'Ruins': c('trait').t`Ruins`,
    'Saga': c('trait').t`Saga`,
    'Salem': c('trait').t`Salem`,
    'Sanctum': c('trait').t`Sanctum`,
    'Scheme': c('trait').t`Scheme`,
    'Scholar': c('trait').t`Scholar`,
    'Science': c('trait').t`Science`,
    'Script': c('trait').t`Script`,
    'Second Floor': c('trait').t`Second Floor`,
    'Sentinel Hill': c('trait').t`Sentinel Hill`,
    'Serpent': c('trait').t`Serpent`,
    'Service': c('trait').t`Service`,
    'Servitor': c('trait').t`Servitor`,
    'Shadow': c('trait').t`Shadow`,
    'Shantak': c('trait').t`Shantak`,
    'Shattered': c('trait').t`Shattered`,
    'Ship': c('trait').t`Ship`,
    'Shoggoth': c('trait').t`Shoggoth`,
    'Silver Twilight': c('trait').t`Silver Twilight`,
    'Skai': c('trait').t`Skai`,
    'Socialite': c('trait').t`Socialite`,
    'Song': c('trait').t`Song`,
    'Sorcerer': c('trait').t`Sorcerer`,
    'Spectral': c('trait').t`Spectral`,
    'Spell': c('trait').t`Spell`,
    'Spider': c('trait').t`Spider`,
    'Spirit': c('trait').t`Spirit`,
    'St Mary\'s': c('trait').t`St Mary's`,
    'Staff': c('trait').t`Staff`,
    'Steps': c('trait').t`Steps`,
    'Summon': c('trait').t`Summon`,
    'Supply': c('trait').t`Supply`,
    'Surface': c('trait').t`Surface`,
    'Suspect': c('trait').t`Suspect`,
    'Syndicate': c('trait').t`Syndicate`,
    'Synergy': c('trait').t`Synergy`,
    'Tactic': c('trait').t`Tactic`,
    'Talent': c('trait').t`Talent`,
    'Tarot': c('trait').t`Tarot`,
    'Task': c('trait').t`Task`,
    'Temple': c('trait').t`Temple`,
    'Tenochtitlán': c('trait').t`Tenochtitlán`,
    'Tentacle': c('trait').t`Tentacle`,
    'Terror': c('trait').t`Terror`,
    'Third Floor': c('trait').t`Third Floor`,
    'Tindalos': c('trait').t`Tindalos`,
    'Tome': c('trait').t`Tome`,
    'Tool': c('trait').t`Tool`,
    'Town': c('trait').t`Town`,
    'Train': c('trait').t`Train`,
    'Trap': c('trait').t`Trap`,
    'Trick': c('trait').t`Trick`,
    'Unbroken': c('trait').t`Unbroken`,
    'Unhallowed': c('trait').t`Unhallowed`,
    'Upgrade': c('trait').t`Upgrade`,
    'Vale': c('trait').t`Vale`,
    'Vehicle': c('trait').t`Vehicle`,
    'Venice': c('trait').t`Venice`,
    'Veteran': c('trait').t`Veteran`,
    'Void': c('trait').t`Void`,
    'Warden': c('trait').t`Warden`,
    'Wastes': c('trait').t`Wastes`,
    'Wayfarer': c('trait').t`Wayfarer`,
    'Weapon': c('trait').t`Weapon`,
    'Wilderness': c('trait').t`Wilderness`,
    'Witch': c('trait').t`Witch`,
    'Witch House': c('trait').t`Witch House`,
    'Wonderland': c('trait').t`Wonderland`,
    'Woods': c('trait').t`Woods`,
    'Y\'ha-nthlei': c('trait').t`Y'ha-nthlei`,
    'Yithian': c('trait').t`Yithian`,
    'Yoth': c('trait').t`Yoth`,
    'Zoog': c('trait').t`Zoog`,
  };
}
