import { c } from 'ttag';

export default function getLocalizedTraits(): { [trait: string]: string | undefined } {
  return {
    '???': c('trait').t`???`,
    'AI': c('trait').t`AI`,
    'Abandoned': c('trait').t`Abandoned`,
    'Abomination': c('trait').t`Abomination`,
    'Abyss': c('trait').t`Abyss`,
    'Access': c('trait').t`Access`,
    'Act 1': c('trait').t`Act 1`,
    'Act 2': c('trait').t`Act 2`,
    'Agency': c('trait').t`Agency`,
    'Alexandria': c('trait').t`Alexandria`,
    'Allied': c('trait').t`Allied`,
    'Ally': c('trait').t`Ally`,
    'Ally? Creature': c('trait').t`Ally? Creature`,
    'Altered': c('trait').t`Altered`,
    'Ancient': c('trait').t`Ancient`,
    'Ancient One': c('trait').t`Ancient One`,
    'Ancient One?': c('trait').t`Ancient One?`,
    'Arkham': c('trait').t`Arkham`,
    'Arkham Asylum': c('trait').t`Arkham Asylum`,
    'Armor': c('trait').t`Armor`,
    'Artist': c('trait').t`Artist`,
    'Assistant': c('trait').t`Assistant`,
    'Attack': c('trait').t`Attack`,
    'Augury': c('trait').t`Augury`,
    'Avatar': c('trait').t`Avatar`,
    'Bad dog': c('trait').t`Bad dog`,
    'Basement': c('trait').t`Basement`,
    'Bayou': c('trait').t`Bayou`,
    'Bazaar': c('trait').t`Bazaar`,
    'Believer': c('trait').t`Believer`,
    'Blessed': c('trait').t`Blessed`,
    'Blessed?': c('trait').t`Blessed?`,
    'Blight': c('trait').t`Blight`,
    'Blunder': c('trait').t`Blunder`,
    'Boat': c('trait').t`Boat`,
    'Bog': c('trait').t`Bog`,
    'Bokor': c('trait').t`Bokor`,
    'Bold': c('trait').t`Bold`,
    'Book': c('trait').t`Book`,
    'Boon': c('trait').t`Boon`,
    'Bridge': c('trait').t`Bridge`,
    'Broken': c('trait').t`Broken`,
    'Brotherhood': c('trait').t`Brotherhood`,
    'Buenos Aires': c('trait').t`Buenos Aires`,
    'Byakhee': c('trait').t`Byakhee`,
    'Bystander': c('trait').t`Bystander`,
    'Cairo': c('trait').t`Cairo`,
    'Campsite': c('trait').t`Campsite`,
    'Card': c('trait').t`Card`,
    'Carnevale': c('trait').t`Carnevale`,
    'Cart': c('trait').t`Cart`,
    'Case': c('trait').t`Case`,
    'Casino': c('trait').t`Casino`,
    'Castle': c('trait').t`Castle`,
    'Cave': c('trait').t`Cave`,
    'Central': c('trait').t`Central`,
    'Chair': c('trait').t`Chair`,
    'Charm': c('trait').t`Charm`,
    'Chess': c('trait').t`Chess`,
    'Chosen': c('trait').t`Chosen`,
    'Circle': c('trait').t`Circle`,
    'City': c('trait').t`City`,
    'Civic': c('trait').t`Civic`,
    'Clairvoyant': c('trait').t`Clairvoyant`,
    'Classy': c('trait').t`Classy`,
    'Clothing': c('trait').t`Clothing`,
    'Clover Club': c('trait').t`Clover Club`,
    'Coastal': c('trait').t`Coastal`,
    'Collector': c('trait').t`Collector`,
    'Colour': c('trait').t`Colour`,
    'Composure': c('trait').t`Composure`,
    'Condition': c('trait').t`Condition`,
    'Connection': c('trait').t`Connection`,
    'Consort': c('trait').t`Consort`,
    'Conspirator': c('trait').t`Conspirator`,
    'Construct': c('trait').t`Construct`,
    'Corpse': c('trait').t`Corpse`,
    'Corruption': c('trait').t`Corruption`,
    'Coterie': c('trait').t`Coterie`,
    'Covenant': c('trait').t`Covenant`,
    'Creature': c('trait').t`Creature`,
    'Crew': c('trait').t`Crew`,
    'Crime Scene': c('trait').t`Crime Scene`,
    'Criminal': c('trait').t`Criminal`,
    'Cultist': c('trait').t`Cultist`,
    'Curse': c('trait').t`Curse`,
    'Cursed': c('trait').t`Cursed`,
    'Dark': c('trait').t`Dark`,
    'Dark Young': c('trait').t`Dark Young`,
    'Darkness': c('trait').t`Darkness`,
    'Deep One': c('trait').t`Deep One`,
    'Delta': c('trait').t`Delta`,
    'Depths': c('trait').t`Depths`,
    'Desert': c('trait').t`Desert`,
    'Desperate': c('trait').t`Desperate`,
    'Detective': c('trait').t`Detective`,
    'Developed': c('trait').t`Developed`,
    'Device': c('trait').t`Device`,
    'Dhole': c('trait').t`Dhole`,
    'Dilemma': c('trait').t`Dilemma`,
    'Distortion': c('trait').t`Distortion`,
    'Dormant': c('trait').t`Dormant`,
    'Double': c('trait').t`Double`,
    'Downtown': c('trait').t`Downtown`,
    'Dreamer': c('trait').t`Dreamer`,
    'Dreamlands': c('trait').t`Dreamlands`,
    'Drifter': c('trait').t`Drifter`,
    'Dunwich': c('trait').t`Dunwich`,
    'Eidolon': c('trait').t`Eidolon`,
    'Elder Thing': c('trait').t`Elder Thing`,
    'Eldritch': c('trait').t`Eldritch`,
    'Elite': c('trait').t`Elite`,
    'Emissary': c('trait').t`Emissary`,
    'Endtimes': c('trait').t`Endtimes`,
    'Enigma': c('trait').t`Enigma`,
    'Entrance': c('trait').t`Entrance`,
    'Entrepreneur': c('trait').t`Entrepreneur`,
    'Evidence': c('trait').t`Evidence`,
    'Exhibit': c('trait').t`Exhibit`,
    'Expedition': c('trait').t`Expedition`,
    'Expert': c('trait').t`Expert`,
    'Extradimensional': c('trait').t`Extradimensional`,
    'Extraterrestrial': c('trait').t`Extraterrestrial`,
    'Eztli': c('trait').t`Eztli`,
    'Fairy': c('trait').t`Fairy`,
    'Falcon Point': c('trait').t`Falcon Point`,
    'Familiar': c('trait').t`Familiar`,
    'Farm': c('trait').t`Farm`,
    'Fated': c('trait').t`Fated`,
    'Favor': c('trait').t`Favor`,
    'Fellow Dogs': c('trait').t`Fellow Dogs`,
    'Field': c('trait').t`Field`,
    'Firearm': c('trait').t`Firearm`,
    'Flaw': c('trait').t`Flaw`,
    'Flora': c('trait').t`Flora`,
    'Footwear': c('trait').t`Footwear`,
    'Footwear, but not really': c('trait').t`Footwear, but not really`,
    'Forbidden': c('trait').t`Forbidden`,
    'Forest': c('trait').t`Forest`,
    'Forgotten': c('trait').t`Forgotten`,
    'Fortune': c('trait').t`Fortune`,
    'Future': c('trait').t`Future`,
    'Gambit': c('trait').t`Gambit`,
    'Game': c('trait').t`Game`,
    'Geist': c('trait').t`Geist`,
    'Ghast': c('trait').t`Ghast`,
    'Ghoul': c('trait').t`Ghoul`,
    'Glacier': c('trait').t`Glacier`,
    'Government': c('trait').t`Government`,
    'Grant': c('trait').t`Grant`,
    'Graveyard': c('trait').t`Graveyard`,
    'Ground Floor': c('trait').t`Ground Floor`,
    'Guest': c('trait').t`Guest`,
    'Gug': c('trait').t`Gug`,
    'Hall': c('trait').t`Hall`,
    'Hardship': c('trait').t`Hardship`,
    'Haunted': c('trait').t`Haunted`,
    'Havana': c('trait').t`Havana`,
    'Hazard': c('trait').t`Hazard`,
    'Hemlock Vale': c('trait').t`Hemlock Vale`,
    'Hex': c('trait').t`Hex`,
    'Hideout': c('trait').t`Hideout`,
    'Historical Society': c('trait').t`Historical Society`,
    'Human': c('trait').t`Human`,
    'Humanoid': c('trait').t`Humanoid`,
    'Hunter': c('trait').t`Hunter`,
    'Hybrid': c('trait').t`Hybrid`,
    'Illicit': c('trait').t`Illicit`,
    'Improvised': c('trait').t`Improvised`,
    'Inconspicuous': c('trait').t`Inconspicuous`,
    'Infection': c('trait').t`Infection`,
    'Injury': c('trait').t`Injury`,
    'Innate': c('trait').t`Innate`,
    'Innocent': c('trait').t`Innocent`,
    'Innsmouth': c('trait').t`Innsmouth`,
    'Insect': c('trait').t`Insect`,
    'Insight': c('trait').t`Insight`,
    'Instrument': c('trait').t`Instrument`,
    'Island': c('trait').t`Island`,
    'Istanbul': c('trait').t`Istanbul`,
    'Item': c('trait').t`Item`,
    'Job': c('trait').t`Job`,
    'Jungle': c('trait').t`Jungle`,
    'Kadath': c('trait').t`Kadath`,
    'Key': c('trait').t`Key`,
    'Kingsport': c('trait').t`Kingsport`,
    'Kuala Lumpur': c('trait').t`Kuala Lumpur`,
    'Lair': c('trait').t`Lair`,
    'Lantern Club': c('trait').t`Lantern Club`,
    'Lead': c('trait').t`Lead`,
    'Leader': c('trait').t`Leader`,
    'Leng': c('trait').t`Leng`,
    'Lit': c('trait').t`Lit`,
    'Local': c('trait').t`Local`,
    'Locus Site': c('trait').t`Locus Site`,
    'Lodge': c('trait').t`Lodge`,
    'London': c('trait').t`London`,
    'Loyal': c('trait').t`Loyal`,
    'Lunatic': c('trait').t`Lunatic`,
    'Machination': c('trait').t`Machination`,
    'Machine': c('trait').t`Machine`,
    'Madness': c('trait').t`Madness`,
    'Madness?': c('trait').t`Madness?`,
    'Mainland': c('trait').t`Mainland`,
    'Manifold': c('trait').t`Manifold`,
    'Manor': c('trait').t`Manor`,
    'Marrakesh': c('trait').t`Marrakesh`,
    'Mask': c('trait').t`Mask`,
    'Medic': c('trait').t`Medic`,
    'Medical': c('trait').t`Medical`,
    'Melee': c('trait').t`Melee`,
    'Mexico City': c('trait').t`Mexico City`,
    'Mi-Go': c('trait').t`Mi-Go`,
    'Miasma': c('trait').t`Miasma`,
    'Midtown': c('trait').t`Midtown`,
    'Mirage': c('trait').t`Mirage`,
    'Misfortune': c('trait').t`Misfortune`,
    'Miskatonic': c('trait').t`Miskatonic`,
    'Mnar': c('trait').t`Mnar`,
    'Monster': c('trait').t`Monster`,
    'Montréal': c('trait').t`Montréal`,
    'Mountain': c('trait').t`Mountain`,
    'Mountains': c('trait').t`Mountains`,
    'Music': c('trait').t`Music`,
    'Musician': c('trait').t`Musician`,
    'Mutated': c('trait').t`Mutated`,
    'Mystery': c('trait').t`Mystery`,
    'New Orleans': c('trait').t`New Orleans`,
    'New York City': c('trait').t`New York City`,
    'Nightgaunt': c('trait').t`Nightgaunt`,
    'Northside': c('trait').t`Northside`,
    'Nostalgia II': c('trait').t`Nostalgia II`,
    'Obstacle': c('trait').t`Obstacle`,
    'Occult': c('trait').t`Occult`,
    'Ocean': c('trait').t`Ocean`,
    'Omen': c('trait').t`Omen`,
    'Ooth-Nargai': c('trait').t`Ooth-Nargai`,
    'Ooze': c('trait').t`Ooze`,
    'Oozified': c('trait').t`Oozified`,
    'Oriab': c('trait').t`Oriab`,
    'Otherworld': c('trait').t`Otherworld`,
    'Outsider': c('trait').t`Outsider`,
    'Oz': c('trait').t`Oz`,
    'Pact': c('trait').t`Pact`,
    'Paradox': c('trait').t`Paradox`,
    'Parasitic': c('trait').t`Parasitic`,
    'Paris': c('trait').t`Paris`,
    'Part 1': c('trait').t`Part 1`,
    'Passageway': c('trait').t`Passageway`,
    'Past': c('trait').t`Past`,
    'Patron': c('trait').t`Patron`,
    'Performer': c('trait').t`Performer`,
    'Plains': c('trait').t`Plains`,
    'Plot': c('trait').t`Plot`,
    'Pnakotus': c('trait').t`Pnakotus`,
    'Poison': c('trait').t`Poison`,
    'Police': c('trait').t`Police`,
    'Port': c('trait').t`Port`,
    'Portal': c('trait').t`Portal`,
    'Possessed': c('trait').t`Possessed`,
    'Power': c('trait').t`Power`,
    'Practiced': c('trait').t`Practiced`,
    'Present': c('trait').t`Present`,
    'Present-Day': c('trait').t`Present-Day`,
    'Priestess': c('trait').t`Priestess`,
    'Prison': c('trait').t`Prison`,
    'Private': c('trait').t`Private`,
    'Providence': c('trait').t`Providence`,
    'Public': c('trait').t`Public`,
    'Pup': c('trait').t`Pup`,
    'Rail': c('trait').t`Rail`,
    'Ranged': c('trait').t`Ranged`,
    'Relic': c('trait').t`Relic`,
    'Reporter': c('trait').t`Reporter`,
    'Research': c('trait').t`Research`,
    'Resident': c('trait').t`Resident`,
    'Resolute': c('trait').t`Resolute`,
    'Resonant': c('trait').t`Resonant`,
    'Restricted': c('trait').t`Restricted`,
    'Retired': c('trait').t`Retired`,
    'Return': c('trait').t`Return`,
    'Risen': c('trait').t`Risen`,
    'Ritual': c('trait').t`Ritual`,
    'Ritual Site': c('trait').t`Ritual Site`,
    'Rival': c('trait').t`Rival`,
    'River': c('trait').t`River`,
    'Riverside': c('trait').t`Riverside`,
    'Road': c('trait').t`Road`,
    'Role': c('trait').t`Role`,
    'Room': c('trait').t`Room`,
    'Rot': c('trait').t`Rot`,
    'Row': c('trait').t`Row`,
    'Royalty': c('trait').t`Royalty`,
    'Ruins': c('trait').t`Ruins`,
    'Saga': c('trait').t`Saga`,
    'Salem': c('trait').t`Salem`,
    'Sanctum': c('trait').t`Sanctum`,
    'Scheme': c('trait').t`Scheme`,
    'Scholar': c('trait').t`Scholar`,
    'Science': c('trait').t`Science`,
    'Scientist': c('trait').t`Scientist`,
    'Scion': c('trait').t`Scion`,
    'Script': c('trait').t`Script`,
    'Second Floor': c('trait').t`Second Floor`,
    'Sentinel Hill': c('trait').t`Sentinel Hill`,
    'Serpent': c('trait').t`Serpent`,
    'Service': c('trait').t`Service`,
    'Servitor': c('trait').t`Servitor`,
    'Shadow': c('trait').t`Shadow`,
    'Shantak': c('trait').t`Shantak`,
    'Shapeshifter': c('trait').t`Shapeshifter`,
    'Shattered': c('trait').t`Shattered`,
    'Sheldon Gang': c('trait').t`Sheldon Gang`,
    'Ship': c('trait').t`Ship`,
    'Shoggoth': c('trait').t`Shoggoth`,
    'Silver Twilight': c('trait').t`Silver Twilight`,
    'Sister': c('trait').t`Sister`,
    'Skai': c('trait').t`Skai`,
    'Slope': c('trait').t`Slope`,
    'Socialite': c('trait').t`Socialite`,
    'Soldier': c('trait').t`Soldier`,
    'Song': c('trait').t`Song`,
    'Sorcerer': c('trait').t`Sorcerer`,
    'Spectral': c('trait').t`Spectral`,
    'Spell': c('trait').t`Spell`,
    'Spider': c('trait').t`Spider`,
    'Spirit': c('trait').t`Spirit`,
    'St Mary\'s': c('trait').t`St Mary's`,
    'Stable': c('trait').t`Stable`,
    'Staff': c('trait').t`Staff`,
    'Station': c('trait').t`Station`,
    'Steps': c('trait').t`Steps`,
    'Stop': c('trait').t`Stop`,
    'Sub-Level': c('trait').t`Sub-Level`,
    'Summon': c('trait').t`Summon`,
    'Sunken': c('trait').t`Sunken`,
    'Supply': c('trait').t`Supply`,
    'Surface': c('trait').t`Surface`,
    'Suspect': c('trait').t`Suspect`,
    'Syndicate': c('trait').t`Syndicate`,
    'Synergy': c('trait').t`Synergy`,
    'Table': c('trait').t`Table`,
    'Tactic': c('trait').t`Tactic`,
    'Talent': c('trait').t`Talent`,
    'Tarot': c('trait').t`Tarot`,
    'Task': c('trait').t`Task`,
    'Tatterdemalion': c('trait').t`Tatterdemalion`,
    'Temple': c('trait').t`Temple`,
    'Tenochtitlán': c('trait').t`Tenochtitlán`,
    'Tentacle': c('trait').t`Tentacle`,
    'Terror': c('trait').t`Terror`,
    'That\'s bad': c('trait').t`That's bad`,
    'Third Floor': c('trait').t`Third Floor`,
    'Tindalos': c('trait').t`Tindalos`,
    'Tome': c('trait').t`Tome`,
    'Tool': c('trait').t`Tool`,
    'Tower': c('trait').t`Tower`,
    'Town': c('trait').t`Town`,
    'Train': c('trait').t`Train`,
    'Traitor': c('trait').t`Traitor`,
    'Trap': c('trait').t`Trap`,
    'Trick': c('trait').t`Trick`,
    'Tulgey Wood': c('trait').t`Tulgey Wood`,
    'Unbroken': c('trait').t`Unbroken`,
    'Uncharted': c('trait').t`Uncharted`,
    'Underground': c('trait').t`Underground`,
    'Unhallowed': c('trait').t`Unhallowed`,
    'Unlit': c('trait').t`Unlit`,
    'Unpracticed': c('trait').t`Unpracticed`,
    'Unstable': c('trait').t`Unstable`,
    'Upgrade': c('trait').t`Upgrade`,
    'Upper Floor': c('trait').t`Upper Floor`,
    'Vale': c('trait').t`Vale`,
    'Vehicle': c('trait').t`Vehicle`,
    'Venice': c('trait').t`Venice`,
    'Veteran': c('trait').t`Veteran`,
    'Virtual': c('trait').t`Virtual`,
    'Void': c('trait').t`Void`,
    'Warden': c('trait').t`Warden`,
    'Wastes': c('trait').t`Wastes`,
    'Wayfarer': c('trait').t`Wayfarer`,
    'Weapon': c('trait').t`Weapon`,
    'Weather': c('trait').t`Weather`,
    'What? No': c('trait').t`What? No`,
    'Wilderness': c('trait').t`Wilderness`,
    'Witch': c('trait').t`Witch`,
    'Witch House': c('trait').t`Witch House`,
    'Wonderland': c('trait').t`Wonderland`,
    'Woods': c('trait').t`Woods`,
    'Y\'ha-nthlei': c('trait').t`Y'ha-nthlei`,
    'Yithian': c('trait').t`Yithian`,
    'Yoth': c('trait').t`Yoth`,
    'Yuggoth': c('trait').t`Yuggoth`,
    'Zoog': c('trait').t`Zoog`,
  };
}
