export default {
  factions: [],
  uses: [],
  types: [],
  subTypes: [],
  xpLevels: [],
  traits: [],
  packs: [],
  cycleNames: [],
  slots: [],
  encounters: [],
  illustrators: [],
  xpEnabled: false,
  xp: [0, 5],
  costEnabled: false,
  cost: [0, 6],
  victory: false,
  vengeance: false,
  skillEnabled: false,
  unique: false,
  skillIcons: {
    willpower: false,
    intellect: false,
    combat: false,
    agility: false,
    wild: false,
    doubleIcons: false,
  },
  shroudEnabled: false,
  shroud: [0, 6],
  cluesEnabled: false,
  clues: [0, 6],
  cluesFixed: false,
  enemyKeywordsEnabled: false,
  enemyHealthEnabled: false,
  enemyHealth: [0, 10],
  enemyHealthPerInvestigator: false,
  enemyDamageEnabled: false,
  enemyDamage: [0, 5],
  enemyHorrorEnabled: false,
  enemyHorror: [0, 5],
  enemyFightEnabled: false,
  enemyFight: [0, 6],
  enemyEvadeEnabled: false,
  enemyEvade: [0, 6],
  // Misc traits
  enemyElite: false,
  enemyNonElite: false,
  enemyHunter: false,
  enemyNonHunter: false,
  enemyParley: false,
  enemyRetaliate: false,
  enemyAlert: false,
  enemySpawn: false,
  enemyPrey: false,
  enemyAloof: false,
};
