import {
  Platform,
  PlatformColor,
  DynamicColorIOS,
} from 'react-native';

const darkText = Platform.OS === 'ios' ? PlatformColor('labelColor') : '#111';
const lightText = Platform.OS === 'ios' ? PlatformColor('secondaryLabelColor') : '#444';

export default {
  darkText,
  lightText,
  veryLightText: Platform.OS === 'ios' ? PlatformColor('tertiaryLabelColor'): '#888',
  background: Platform.OS === 'ios' ? PlatformColor('systemBackgroundColor') : 'white',
  lightBackground: Platform.OS === 'ios' ? PlatformColor('systemFillColor') : '#ccc',
  veryLightBackground: Platform.OS === 'ios' ? PlatformColor('secondarySystemBackgroundColor') : '#eee',
  veryVeryLightBackgound: Platform.OS === 'ios' ? PlatformColor('tertiarySystemBackgroundColor') : '#f4f4f4',
  divider: Platform.OS === 'ios' ? PlatformColor('separatorColor') : '#bdbdbd',
  faction: {
    mystic: {
      primary: '#4331b9',
      background: '#4331b9',
      dark: '#4331b9',
      veryLight: Platform.OS === 'ios' ? DynamicColorIOS({ light: '#d9d6f1', dark: '#46018f' }) : '#d9d6f1',
      light: Platform.OS === 'ios' ? DynamicColorIOS({ light: '#a198dc', dark: '#6104c4' }) : '#a198dc',
    },
    seeker: {
      primary: '#ec8426',
      background: '#ec8426',
      dark: '#ec8426',
      veryLight: Platform.OS === 'ios' ? DynamicColorIOS({ light: '#fbe6d4', dark: '#cf6b0e' }) : '#f7cea8',
      light: Platform.OS === 'ios' ? DynamicColorIOS({ light: '#f7cea8', dark: '#de6f09' }) : '#f7cea8',
    },
    guardian: {
      primary: '#2b80c5',
      background: '#2b80c5',
      dark: '#2b80c5',
      veryLight: Platform.OS === 'ios' ? DynamicColorIOS({ light: '#d5e6f3', dark: '#004880' }) : '#d5e6f3',
      light: Platform.OS === 'ios' ? DynamicColorIOS({ light: '#aacce8', dark: '#0062ad' }) : '#aacce8',
    },
    rogue: {
      primary: '#107116',
      background: '#107116',
      dark: '#107116',
      veryLight: Platform.OS === 'ios' ? DynamicColorIOS({ light: '#cfe3d0', dark: '#015906' }) : '#cfe3d0',
      light: Platform.OS === 'ios' ? DynamicColorIOS({ light: '#9fc6a2', dark: '#008207' }) : '#9fc6a2', 
    },
    survivor: {
      primary: '#cc3038',
      background: '#cc3038',
      dark: '#cc3038',
      veryLight: Platform.OS === 'ios' ? DynamicColorIOS({ light: '#f5d6d7', dark: '#7a0105' }) : '#f5d6d7', 
      light: Platform.OS === 'ios' ? DynamicColorIOS({ light: '#ebacaf', dark: '#b30006' }) : '#ebacaf',
    },
    neutral: {
      primary: darkText,
      background: Platform.OS === 'ios' ? DynamicColorIOS({ light: '#444444', dark: '#bbb' }) : '#444',
      dark: Platform.OS === 'ios' ? DynamicColorIOS({ light: '#444444', dark: '#bbb' }) : '#444',
      veryLight: Platform.OS === 'ios' ? DynamicColorIOS({ light: '#e6e6e6', dark: '#292929' }) : '#e6e6e6',
      light: Platform.OS === 'ios' ? DynamicColorIOS({ light: '#ccc', dark: '#404040' }) : '#ccc',
    },
    dual: {
      primary: '#868600',
      background: '#9a9a00',
      dark: '#c0c000',
      veryLight: '#f2f2cc',
      light: '#e6e699',
    },
    dead: {
      primary: '#704214',
      background: '#704214',
      dark: '#5a3510',
      veryLight: '#d4c6b9',
      light: '#b8a18a',
    },
    mythos: {
      primary: darkText,
      background: '#000000',
      dark: '#000000',
      veryLight: '#000000',
      light: '#000000',
    },
  },
  skill: {
    willpower: {
      default: '#003961',
      light: '#506A85',
    },
    intellect: {
      default: '#4e1a45',
      light: '#7B5373',
    },
    combat: {
      default: '#661e09',
      light: '#8D5648',
    },
    agility: {
      default: '#00543a',
      light: '#417F6C',
    },
    wild: {
      default: '#635120',
      light: '#8A7D5A',
    },
  },
  scenarioGreen: '#2E5344',
  veryLightBlue: '#cce4ff',
  lightBlue: '#007AFF',
  darkBlue: 'rgb(0, 78, 100)',
  white: 'rgb(247, 247, 255)',
  red: '#D84144',
  lightGray: 'rgb(230, 230, 230)',
  veryLightGray: 'rgb(245, 245, 245)',
  gray: 'rgb(201, 201, 201)',
  darkGray: 'rgb(120, 120, 120)',
  lightGreen: 'rgb(114, 221, 82)',
  yellow: 'rgb(255, 204, 0)',
  taboo: 'purple',
  green: '#498D35',
  button: Platform.OS === 'ios' ? '#bbb' : '#000',
  navButton: Platform.OS === 'ios' ? PlatformColor('linkColor') : '#000',
  black: '#000',
  switchTrackColor: Platform.OS === 'ios' ? { false: '#bbb', true: '#222' } : undefined,
  settingsBackground: Platform.OS === 'ios' ? '#e3e6ed' : 'rgb(247, 247, 255)',
  monza: '#C70039',
};
