require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'ArkhamCards' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  target 'ArkhamCardsUITests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  #add_flipper_pods!
  #post_install do |installer|
  #  flipper_post_install(installer)
  #end
end

