export default {
  factions: [],
  uses: [],
  types: [],
  subTypes: [],
  xpLevels: [],
  traits: [],
  packs: [],
  cycleNames: [],
  slots: [],
  encounters: [],
  illustrators: [],
  xpEnabled: false,
  xp: [0, 5],
  costEnabled: false,
  cost: [0, 6],
  nonElite: false,
  victory: false,
  vengeance: false,
  skillEnabled: false,
  skillIcons: {
    willpower: false,
    intellect: false,
    combat: false,
    agility: false,
    wild: false,
    doubleIcons: false,
  },
};
