export default {
  factions: [],
  types: [],
  subTypes: [],
  xpLevels: [],
  traits: [],
  packs: [],
  slots: [],
  encounters: [],
  illustrators: [],
  nonElite: false,
  victory: false,
  vengeance: false,
  willpower: false,
  intellect: false,
  combat: false,
  agility: false,
  wild: false,
  doubleIcons: false,
};
