export const CUSTOM = 'custom';

export const CAMPAIGN_SCENARIOS = {
  'core': [
    { name: 'The Gathering', code: 'torch', pack_code: 'core' },
    { name: 'The Midnight Masks', code: 'arkham', pack_code: 'core' },
    { name: 'The Devourer Below', code: 'tentacles', pack_code: 'core' },
  ],
  'dwl': [
    { name: 'Extracurricular Activity', code: 'extracurricular_activity', pack_code: 'dwl' },
    { name: 'The House Always Wins', code: 'the_house_always_wins', pack_code: 'dwl' },
    { name: 'Armitage’s Fate', code: 'armitages_fate', interlude: true },
    { name: 'The Miskatonic Museum', code: 'the_miskatonic_museum', pack_code: 'tmm' },
    { name: 'Essex County Express', code: 'essex_county_express', pack_code: 'tece' },
    { name: 'Blood on the Altar', code: 'blood_on_the_altar', pack_code: 'bota' },
    { name: 'The Survivors', code: 'dwl_interlude2', interlude: true },
    { name: 'Undimensioned and Unseen', code: 'undimensioned_and_unseen', pack_code: 'uau' },
    { name: 'Where Doom Awaits', code: 'where_doom_awaits', pack_code: 'wda' },
    { name: 'Lost in Time and Space', code: 'lost_in_time_and_space', pack_code: 'litas' },
    { name: 'Epilogue', code: 'dwl_epilogue', interlude: true },
  ],
  'ptc': [
    { name: 'Prologue', code: 'ptc_prologue', interlude: true },
    { name: 'Curtain Call', code: 'curtain_call', pack_code: 'ptc' },
    { name: 'The Last King', code: 'the_last_king', pack_code: 'ptc' },
    { name: 'Lunacy’s Reward', code: 'ptc_interlude1', interlude: true },
    { name: 'Echoes of the Past', code: 'echoes_of_the_past', pack_code: 'eotp' },
    { name: 'The Unspeakable Oath', code: 'the_unspeakable_oath', pack_code: 'tuo' },
    { name: 'Lost Soul', code: 'ptc_interlude2', interlude: true },
    { name: 'A Phantom of Truth', code: 'a_phantom_of_truth', pack_code: 'apot' },
    { name: 'The Pallid Mask', code: 'the_pallid_mask', pack_code: 'tpm' },
    { name: 'Black Stars Rise', code: 'black_stars_rise', pack_code: 'bsr' },
    { name: 'Dim Carcosa', code: 'dim_carcosa', pack_code: 'dca' },
    { name: 'Epilogue', code: 'ptc_epilogue', interlude: true },
  ],
  'tfa': [
    { name: 'Prologue', code: 'tfa_prologue', interlude: true },
    { name: 'The Untamed Wilds', code: 'wilds', pack_code: 'tfa' },
    { name: 'Restless Nights', code: 'tfa_interlude1', interlude: true },
    { name: 'The Doom of Eztli', code: 'eztli', pack_code: 'tfa' },
    { name: 'Expedition’s End', code: 'tfa_interlude2', interlude: true },
    { name: 'Threads of Fate', code: 'threads_of_fate', pack_code: 'tof' },
    { name: 'The Boundary Beyond', code: 'the_boundary_beyond', pack_code: 'tbb' },
    { name: 'The Jungle Beckons', code: 'tfa_interlude3', interlude: true },
    { name: 'Heart of the Elders', code: 'heart_of_the_elders', pack_code: 'hote' },
    { name: 'The City of Archives', code: 'the_city_of_archives', pack_code: 'tcoa' },
    { name: 'Those Held Captive', code: 'tfa_interlude4', interlude: true },
    { name: 'The Depths of Yoth', code: 'the_depths_of_yoth', pack_code: 'tdoy' },
    { name: 'The Darkness', code: 'tfa_interlude5', interlude: true },
    { name: 'Shattered Aeons', code: 'shattered_aeons', pack_code: 'sha' },
    { name: 'Epilogue', code: 'tfa_epilogue', interlude: true },
  ],
  'rtnotz': [
    { name: 'Return to The Gathering', code: 'return_to_the_gathering', pack_code: 'rtnotz' },
    { name: 'Return to the Midnight Masks', code: 'return_to_the_midnight_masks', pack_code: 'rtnotz' },
    { name: 'Return to the Devourer Below', code: 'return_to_the_devourer_below', pack_code: 'rtnotz' },
  ],
};
